# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-02 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_merge'),
        ('config', '0002_auto_20180731_1718'),
    ]

    operations = [
    ]
