# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-02 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180731_1718'),
        ('exercises', '0006_merge'),
    ]

    operations = [
    ]
