# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-02 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20180731_1718'),
        ('nutrition', '0002_auto_20180731_1244'),
    ]

    operations = [
    ]
