# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-02 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealitem',
            old_name='meal_choice',
            new_name='status_choice',
        ),
    ]
