# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-03 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymconfig',
            name='weeks_inactive',
            field=models.PositiveIntegerField(default=4, help_text='Number of weeks since the last time a userlogged his presence to be considered inactive', verbose_name='Reminder of inactive members'),
        ),
    ]
