# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-02 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180731_1244'),
        ('core', '0010_auto_20180731_1718'),
    ]

    operations = [
    ]
