# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-02 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_merge'),
        ('manager', '0008_auto_20180731_1718'),
    ]

    operations = [
    ]
