# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-23 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='workout_session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession', verbose_name='workout_session_id'),
        ),
    ]
