# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-20 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='period',
            field=models.CharField(choices=[('null', 'No period'), ('Microcycle', 'Microcycle i.e 1 week'), ('Mesocycle', 'Mesocycle i.e 2-6 weeks'), ('Macrocycle', 'Macrocycle i.e 1 year')], default='null', max_length=50, null=True, verbose_name='Period'),
        ),
    ]
